import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({ component: Terms });

function Terms() {
	return (
		<div className="bg-background text-foreground">
			<section className="py-12 px-6">
				<article className="mx-auto max-w-3xl prose-sm sm:prose prose-invert">
					<h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
					<p className="text-sm text-muted-foreground mb-8">
						Last updated: April 17, 2026
					</p>

					<h2 className="text-xl font-semibold mt-8 mb-3">
						1. Acceptance of Terms
					</h2>
					<p className="mb-4">
						By accessing or using steakholderagent.org (the "Service"), you
						agree to be bound by these Terms of Service ("Terms"). If you do not
						agree, please do not use the Service.
					</p>

					<h2 className="text-xl font-semibold mt-8 mb-3">
						2. Description of the Service
					</h2>
					<p className="mb-4">
						The Service is provided for academic and educational purposes only.
						It is intended to support teaching, learning, and research. The
						Service is not intended for commercial use or for any activity
						outside of these educational contexts.
					</p>

					<h2 className="text-xl font-semibold mt-8 mb-3">3. Eligibility</h2>
					<p className="mb-4">
						You may use the Service only if you can form a binding contract
						under applicable law and are not barred from using the Service. If
						you are using the Service as part of a course or program, your
						institution's policies may also apply.
					</p>

					<h2 className="text-xl font-semibold mt-8 mb-3">4. Accounts</h2>
					<p className="mb-4">
						You are responsible for maintaining the confidentiality of your
						account credentials and for all activity that occurs under your
						account. Notify us promptly of any unauthorized use or suspected
						security breach.
					</p>

					<h2 className="text-xl font-semibold mt-8 mb-3">5. Acceptable Use</h2>
					<p className="mb-2">You agree not to use the Service to:</p>
					<ul className="list-disc pl-6 mb-4 space-y-1">
						<li>Violate any applicable law or regulation.</li>
						<li>
							Infringe on the intellectual property, privacy, or other rights of
							others.
						</li>
						<li>
							Upload or transmit malicious code, spam, or harmful content.
						</li>
						<li>
							Attempt to gain unauthorized access to the Service, other
							accounts, or related systems.
						</li>
						<li>
							Use the Service for commercial resale, advertising, or
							non-academic purposes.
						</li>
						<li>
							Interfere with or disrupt the integrity or performance of the
							Service.
						</li>
					</ul>

					<h2 className="text-xl font-semibold mt-8 mb-3">6. User Content</h2>
					<p className="mb-4">
						You retain ownership of any content you submit to the Service. By
						submitting content, you grant us a limited, non-exclusive license to
						host, display, and process that content solely for the purpose of
						operating the Service and supporting academic use. You are
						responsible for the content you submit and for ensuring you have the
						rights to share it.
					</p>

					<h2 className="text-xl font-semibold mt-8 mb-3">
						7. Intellectual Property
					</h2>
					<p className="mb-4">
						The Service, including its design, code, and branding, is owned by
						steakholderagent.org and its contributors and is protected by
						applicable intellectual property laws. You may not copy, modify, or
						create derivative works of the Service except as permitted for
						personal academic use.
					</p>

					<h2 className="text-xl font-semibold mt-8 mb-3">
						8. AI-Generated Content
					</h2>
					<p className="mb-4">
						The Service may produce responses generated by artificial
						intelligence. Such output may contain inaccuracies and should not be
						relied upon as professional, legal, medical, or financial advice.
						Always verify information before relying on it for academic work or
						other purposes.
					</p>

					<h2 className="text-xl font-semibold mt-8 mb-3">
						9. Disclaimer of Warranties
					</h2>
					<p className="mb-4">
						The Service is provided "as is" and "as available" without
						warranties of any kind, express or implied, including warranties of
						merchantability, fitness for a particular purpose, or
						non-infringement. We do not guarantee that the Service will be
						uninterrupted, error-free, or secure.
					</p>

					<h2 className="text-xl font-semibold mt-8 mb-3">
						10. Limitation of Liability
					</h2>
					<p className="mb-4">
						To the maximum extent permitted by law, steakholderagent.org and its
						contributors will not be liable for any indirect, incidental,
						special, consequential, or punitive damages arising out of your use
						of or inability to use the Service.
					</p>

					<h2 className="text-xl font-semibold mt-8 mb-3">11. Termination</h2>
					<p className="mb-4">
						We may suspend or terminate your access to the Service at any time
						for any reason, including violation of these Terms. You may stop
						using the Service at any time.
					</p>

					<h2 className="text-xl font-semibold mt-8 mb-3">
						12. Changes to These Terms
					</h2>
					<p className="mb-4">
						We may update these Terms from time to time. When we do, we will
						revise the "Last updated" date above. Continued use of the Service
						after changes become effective constitutes acceptance of the updated
						Terms.
					</p>

					<h2 className="text-xl font-semibold mt-8 mb-3">13. Contact</h2>
					<p className="mb-4">
						If you have questions about these Terms, please contact us at
						aperez041@regis.edu.
					</p>
				</article>
			</section>
		</div>
	);
}
